---
  - hosts: web_instance
    gather_facts: false
    vars:
      ansible_pipelining: true
    tasks:
    - name: NPM Install
      shell: |
            cd /home/ec2-user/simple-node-app
            npm install express
      register: result
    - name: Start Application
      shell: |
            cd /home/ec2-user/simple-node-app
            pm2 stop app
            pm2 start app.js
      register: result
    - name: Status Application
      shell: |
            cd /home/ec2-user/simple-node-app
            pm2 status
      register: result