---
  - hosts: web_instance
    gather_facts: false
    vars:
      ansible_pipelining: true
    tasks:
    - name: Pulling Image from Docker Hub 
      shell: |
            docker pull suryansh1234/my-repo:simple-node-app
    - name: Start Application
      shell: |
            docker run --name node-app -p 3000:3000 -d suryansh1234/my-repo:simple-node-app
      register: result
    - name: Status Output
      debug: var=result.stdout_lines