---
  - hosts: web_instance
    vars:
      ansible_pipelining: true
    tasks:
    - name: Start Application
      shell: |
            cd /home/ec2-user/simple-node-app
            npm install express
            pm2 stop app
            pm2 start app.js
      register: result
    - name: Status Application
      shell: |
            cd /home/ec2-user/simple-node-app
            pm2 status
      register: result