name: EC2-Workflow
on:
  workflow_dispatch:
    inputs:
      command: 
        description: Choose whether to apply or destroy
        required: true
        default: apply
        type: choice
        options:
        - apply
        - destroy

env:
  ROLE_NAME : ${{secrets.ROLE_NAME}}
permissions:
  id-token: write  
  contents: read
jobs:
  TERRAFORM_PLAN_APPLY:
    if: inputs.command == 'apply'
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repo
      uses: actions/checkout@main
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{secrets.ROLE_NAME}} 
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: us-east-1
    - name: Creating EC2
      run: |
          cd terraform
          terraform init
          terraform plan -var="role=$ROLE_NAME"
          terraform apply -var="role=$ROLE_NAME" --auto-approve
  TERRAFORM_PLAN_DESTROY:
    if: inputs.command == 'destroy'
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repo
      uses: actions/checkout@main
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{secrets.ROLE_NAME}} 
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: us-east-1
    - name: Destroying EC2
      run: |
          cd terraform
          terraform init
          terraform plan -var="role=$ROLE_NAME"
          terraform destroy -var="role=$ROLE_NAME" --auto-approve